import { AiApp, Comment, HelpOffer, Session } from './types';

const s3 = (key: string) => `https://shitty-ai-apps-assets.s3.amazonaws.com/${key}`;

const avatar = (seed: string) => `https://picsum.photos/seed/${seed}/64/64`;

function contributor(id: string, name: string): AiApp['contributors'][number] {
  return { id, name, avatarUrl: avatar(id) };
}

export const APPS: AiApp[] = [
  // --- User Owned Apps (John Doe / user_123) ---
  {
    id: '1',
    slug: 'perplexity',
    name: 'Perplexity',
    emoji: '🔎',
    tagline: 'AI-powered search that answers questions with sources.',
    about:
      'Ask questions in natural language and get synthesized answers backed by citations from across the web.',
    story:
      'Built around the idea that finding an answer should feel more like asking a knowledgeable researcher than digging through search results.',
    coverImageUrl: s3('covers/perplexity.png'),
    coverTheme: 'dark',
    coverHeadline: 'Where knowledge begins',
    builtWith: 'AI search + web retrieval',
    techStack: ['LLMs', 'Search', 'RAG', 'Web'],
    websiteUrl: 'https://www.perplexity.ai',
    users: 14200,
    mrr: 12400,
    category: 'Productivity',
    upvotes: 484,
    contributors: [
      contributor('user_123', 'John Doe'),
      contributor('c18', 'Chloe Bennett'),
    ],
    needsHelpWith: 'Citation verification pipelines & fast web indexing',
    contactEmail: 'john@example.com',
    launchedAt: '2022-08-01',
    helpCategories: [
      { id: 'h1', label: 'Backend / Infra', peopleCount: 88, avatarUrl: avatar('h1') },
      { id: 'h2', label: 'Search / ML', peopleCount: 54, avatarUrl: avatar('h2') },
    ],
  },
  {
    id: '9',
    slug: 'prompt-smith',
    name: 'PromptSmith',
    emoji: '🔨',
    tagline: 'Automated test suite and regression runner for LLM prompts.',
    about:
      'Unit test your system prompts across multiple model providers, temperature settings, and edge-case test benches before shipping to production.',
    story:
      'Tired of fixing one edge-case prompt bug only to break five others, we created a CI/CD-style test runner for prompts.',
    coverImageUrl: s3('covers/prompt-smith.png'),
    coverTheme: 'mint',
    coverHeadline: 'Never break a prompt in prod',
    builtWith: 'Next.js, LangSmith & OpenRouter',
    techStack: ['TypeScript', 'Next.js', 'LLM Eval', 'Tailwind'],
    websiteUrl: 'https://promptsmith.dev',
    users: 3200,
    mrr: 4800,
    category: 'Dev Tools',
    upvotes: 295,
    contributors: [
      contributor('user_123', 'John Doe'),
      contributor('c9', 'Elena Rostova'),
    ],
    needsHelpWith: 'Few-shot prompt evaluation benches and red-teaming datasets',
    contactEmail: 'john@example.com',
    launchedAt: '2024-03-15',
    helpCategories: [
      { id: 'h3', label: 'Eval & Benchmarking', peopleCount: 42, avatarUrl: avatar('h3') },
      { id: 'h4', label: 'Security / Red-team', peopleCount: 29, avatarUrl: avatar('h4') },
    ],
  },
  {
    id: '10',
    slug: 'meme-forge',
    name: 'MemeForge',
    emoji: '🎭',
    tagline: 'Instant AI video and image meme generator from current trends.',
    about:
      'Monitors trending topics across X, Reddit, and TikTok to automatically compose captioned memes, reaction videos, and parody shorts.',
    story:
      'Started as a weekend hack during a hackathon to automate shitposting, now generating hundreds of thousands of memes every month.',
    coverImageUrl: s3('covers/meme-forge.png'),
    coverTheme: 'sunset',
    coverHeadline: 'Shitpost at the speed of light',
    builtWith: 'FFmpeg WebAssembly & Claude 3.5',
    techStack: ['Remotion', 'WebAssembly', 'Claude', 'Redis'],
    websiteUrl: 'https://memeforge.ai',
    users: 8900,
    mrr: 2150,
    category: 'Fun',
    upvotes: 410,
    contributors: [
      contributor('user_123', 'John Doe'),
      contributor('c12', 'Liam O Connor'),
    ],
    needsHelpWith: 'FFmpeg WebAssembly rendering speed & viral template curation',
    contactEmail: 'john@example.com',
    launchedAt: '2024-05-10',
    helpCategories: [
      { id: 'h5', label: 'Video / FFmpeg', peopleCount: 36, avatarUrl: avatar('h5') },
      { id: 'h6', label: 'Viral Marketing', peopleCount: 65, avatarUrl: avatar('h6') },
    ],
  },
  {
    id: '11',
    slug: 'code-napkin',
    name: 'CodeNapkin',
    emoji: '📝',
    tagline: 'Sketch system diagrams on canvas and get production Terraform & Docker.',
    about:
      'Draw architecture boxes, databases, queues, and gateways on an infinite canvas, and let AI generate complete Infrastructure-as-Code setups.',
    story:
      'Everyone designs architecture on digital whiteboards; translating that into cloud configuration files should be instant.',
    coverImageUrl: s3('covers/code-napkin.png'),
    coverTheme: 'light',
    coverHeadline: 'Draw architecture, ship cloud',
    builtWith: 'Tldraw + Anthropic API',
    techStack: ['Tldraw', 'React', 'Terraform', 'Docker'],
    websiteUrl: 'https://codenapkin.io',
    users: 4500,
    mrr: 6700,
    category: 'Dev Tools',
    upvotes: 380,
    contributors: [contributor('user_123', 'John Doe')],
    needsHelpWith: null,
    launchedAt: '2023-11-20',
    helpCategories: [],
  },
  {
    id: '12',
    slug: 'sleep-bot',
    name: 'SleepBot',
    emoji: '🌙',
    tagline: 'Personalized sleep chronotype coaching synced with smart wearables.',
    about:
      'Connect your Oura Ring, Apple Watch, or Whoop to receive contextual, scientifically grounded recovery recommendations and wind-down nudges.',
    story:
      'Most sleep trackers just give you a guilt score. SleepBot gives you actionable instructions based on your chronobiology.',
    coverImageUrl: s3('covers/sleep-bot.png'),
    coverTheme: 'dark',
    coverHeadline: 'Wake up fully restored',
    builtWith: 'FastAPI, PyTorch & HealthKit',
    techStack: ['HealthKit', 'Oura API', 'Python', 'React Native'],
    websiteUrl: 'https://sleepbot.app',
    users: 2900,
    mrr: 3100,
    category: 'Lifestyle',
    upvotes: 240,
    contributors: [
      contributor('user_123', 'John Doe'),
      contributor('c19', 'Lucas Meyer'),
    ],
    needsHelpWith: 'Wearable data syncing (Garmin & Polar API) and circadian widgets',
    contactEmail: 'john@example.com',
    launchedAt: '2024-01-18',
    helpCategories: [
      { id: 'h7', label: 'Mobile SDKs', peopleCount: 31, avatarUrl: avatar('h7') },
    ],
  },
  {
    id: '13',
    slug: 'sql-whisperer',
    name: 'SQL Whisperer',
    emoji: '🐬',
    tagline: 'Talk to your warehouse in plain English with schema-guaranteed accuracy.',
    about:
      'Secure enterprise text-to-SQL copilot that indexes your data dictionaries, foreign keys, and query logs to produce 100% dialect-valid queries.',
    story:
      'Executives and product managers shouldn’t need to wait 3 days for a data team ticket just to get monthly churn numbers.',
    coverImageUrl: s3('covers/sql-whisperer.png'),
    coverTheme: 'mint',
    coverHeadline: 'Zero SQL tickets for your data team',
    builtWith: 'Rust, DuckDB & GPT-4o',
    techStack: ['Rust', 'DuckDB', 'PostgreSQL', 'Snowflake'],
    websiteUrl: 'https://sqlwhisperer.com',
    users: 5100,
    mrr: 9400,
    category: 'SaaS',
    upvotes: 430,
    contributors: [contributor('user_123', 'John Doe')],
    needsHelpWith: 'Snowflake / BigQuery connector performance tuning',
    contactEmail: 'john@example.com',
    launchedAt: '2023-09-01',
    helpCategories: [
      { id: 'h8', label: 'Data Engineering', peopleCount: 47, avatarUrl: avatar('h8') },
    ],
  },

  // --- Other Community Apps ---
  {
    id: '2',
    slug: 'cursor',
    name: 'Cursor',
    emoji: '⌨️',
    tagline: 'An AI code editor built for programming with models.',
    about:
      'A code editor with AI deeply integrated into editing, navigation, code generation, and understanding large codebases.',
    story:
      'Reimagines the code editor around collaborating with AI instead of adding AI as a separate chat window.',
    coverImageUrl: s3('covers/cursor.png'),
    coverTheme: 'dark',
    coverHeadline: 'Build software faster',
    builtWith: 'Built for AI-assisted coding',
    techStack: ['TypeScript', 'LLMs', 'Code Search', 'IDE'],
    websiteUrl: 'https://www.cursor.com',
    users: 48000,
    mrr: 28500,
    category: 'Dev Tools',
    upvotes: 890,
    contributors: [contributor('c2', 'Alex Chen')],
    needsHelpWith: null,
    launchedAt: '2023-03-01',
    helpCategories: [],
  },
  {
    id: '3',
    slug: 'v0',
    name: 'v0',
    emoji: '▲',
    tagline: 'Generate working web interfaces from natural language.',
    about:
      'Describe an interface or application and generate editable UI and code that can be iterated on conversationally.',
    story:
      'Turns the early stages of building an interface into a conversation instead of starting from an empty editor.',
    coverImageUrl: s3('covers/v0.png'),
    coverTheme: 'light',
    coverHeadline: 'What can we ship?',
    builtWith: 'Generative UI by Vercel',
    techStack: ['React', 'Next.js', 'Tailwind', 'LLMs'],
    websiteUrl: 'https://v0.dev',
    users: 21500,
    mrr: 16800,
    category: 'Dev Tools',
    upvotes: 720,
    contributors: [contributor('c3', 'Maya Singh')],
    needsHelpWith: 'Design / UX component library extensions & theme presets',
    contactEmail: 'maya@v0.dev',
    launchedAt: '2023-10-01',
    helpCategories: [
      { id: 'h9', label: 'Product Design', peopleCount: 94, avatarUrl: avatar('h9') },
      { id: 'h10', label: 'Frontend', peopleCount: 112, avatarUrl: avatar('h10') },
    ],
  },
  {
    id: '4',
    slug: 'bolt',
    name: 'Bolt',
    emoji: '⚡',
    tagline: 'Build full-stack web apps by talking to AI in the browser.',
    about:
      'Create, edit, run, and deploy fullstack web applications from a browser sandbox using natural-language instructions.',
    story:
      'Brings AI generation and a complete development environment together so an idea can become a running application without leaving the browser.',
    coverImageUrl: s3('covers/bolt.png'),
    coverTheme: 'sunset',
    coverHeadline: 'What do you want to build?',
    builtWith: 'Built by StackBlitz',
    techStack: ['WebContainers', 'JavaScript', 'LLMs', 'Web'],
    websiteUrl: 'https://bolt.new',
    users: 26000,
    mrr: 19500,
    category: 'Dev Tools',
    upvotes: 680,
    contributors: [
      contributor('c4', 'Noah Williams'),
      contributor('user_123', 'John Doe'),
    ],
    needsHelpWith: 'WebContainer caching & developer growth marketing',
    contactEmail: 'noah@bolt.new',
    launchedAt: '2024-10-01',
    helpCategories: [
      { id: 'h11', label: 'Growth / Marketing', peopleCount: 140, avatarUrl: avatar('h11') },
      { id: 'h12', label: 'Systems / WebAssembly', peopleCount: 52, avatarUrl: avatar('h12') },
    ],
  },
  {
    id: '5',
    slug: 'gamma',
    name: 'Gamma',
    emoji: '✨',
    tagline: 'Create presentations, documents, and webpages with AI.',
    about:
      'Generate polished presentations and visual documents from a prompt, then refine the content and layout interactively.',
    story:
      'Reworks presentation creation around generated, responsive content rather than manually arranging individual slides.',
    coverImageUrl: s3('covers/gamma.png'),
    coverTheme: 'mint',
    coverHeadline: 'Ideas in. Beautiful work out.',
    builtWith: 'AI-native presentations',
    techStack: ['LLMs', 'Generative UI', 'Web'],
    websiteUrl: 'https://gamma.app',
    users: 31000,
    mrr: 21000,
    category: 'Productivity',
    upvotes: 560,
    contributors: [contributor('c5', 'Sofia Martin')],
    needsHelpWith: null,
    launchedAt: '2022-08-01',
    helpCategories: [],
  },
  {
    id: '6',
    slug: 'lovable',
    name: 'Lovable',
    emoji: '💜',
    tagline: 'Build apps and websites by chatting with AI.',
    about:
      'Describe a product in natural language and generate a working web application that can be refined through conversation.',
    story:
      'Makes software creation feel closer to describing what you want than manually assembling every part of an application.',
    coverImageUrl: s3('covers/lovable.png'),
    coverTheme: 'light',
    coverHeadline: 'Build something Lovable',
    builtWith: 'AI full-stack app builder',
    techStack: ['React', 'Supabase', 'LLMs', 'Web'],
    websiteUrl: 'https://lovable.dev',
    users: 18500,
    mrr: 14700,
    category: 'Dev Tools',
    upvotes: 510,
    contributors: [contributor('c6', 'Leo Andersson')],
    needsHelpWith: 'Community tutorials & edge functions templates',
    contactEmail: 'leo@lovable.dev',
    launchedAt: '2024-01-01',
    helpCategories: [
      { id: 'h13', label: 'Community / Content', peopleCount: 81, avatarUrl: avatar('h13') },
    ],
  },
  {
    id: '7',
    slug: 'suno',
    name: 'Suno',
    emoji: '🎵',
    tagline: 'Turn an idea into a song with generative AI.',
    about:
      'Generate complete songs from text prompts, including vocals, instrumentation, and lyrics in any musical genre.',
    story:
      'Makes music generation accessible through prompts instead of requiring production software or musical training.',
    coverImageUrl: s3('covers/suno.png'),
    coverTheme: 'sunset',
    coverHeadline: 'Make any song you can imagine',
    builtWith: 'Generative music AI',
    techStack: ['Generative Audio', 'Music', 'LLMs'],
    websiteUrl: 'https://suno.com',
    users: 42000,
    mrr: 24000,
    category: 'Fun',
    upvotes: 750,
    contributors: [contributor('c7', 'Jamie Park')],
    needsHelpWith: null,
    launchedAt: '2023-01-01',
    helpCategories: [],
  },
  {
    id: '8',
    slug: 'granola',
    name: 'Granola',
    emoji: '🥣',
    tagline: 'An AI notepad that turns meeting notes into useful notes.',
    about:
      'Take lightweight notes during meetings while AI uses the transcript to fill in context, organize ideas, and produce a useful summary.',
    story:
      'Designed around augmenting the notes you actually write rather than replacing meetings with another recording bot.',
    coverImageUrl: s3('covers/granola.png'),
    coverTheme: 'mint',
    coverHeadline: 'The AI notepad for meetings',
    builtWith: 'AI-assisted meeting notes',
    techStack: ['Transcription', 'LLMs', 'Desktop'],
    websiteUrl: 'https://www.granola.ai',
    users: 8200,
    mrr: 7300,
    category: 'Productivity',
    upvotes: 390,
    contributors: [
      contributor('c8', 'Taylor Brooks'),
      contributor('user_123', 'John Doe'),
    ],
    needsHelpWith: 'Audio segmentation & offline model fallback',
    contactEmail: 'taylor@granola.ai',
    launchedAt: '2023-01-01',
    helpCategories: [
      { id: 'h14', label: 'Audio Engineering', peopleCount: 45, avatarUrl: avatar('h14') },
    ],
  },
  {
    id: '14',
    slug: 'replit-agent',
    name: 'Replit Agent',
    emoji: '🤖',
    tagline: 'Autonomous AI engineer that builds and deploys software from scratch.',
    about:
      'Spec out full-stack applications and watch the agent create files, install dependencies, spin up databases, and debug errors autonomously.',
    story:
      'Takes generative code to the next logical frontier: agents that self-execute, diagnose compiler failures, and deliver running URLs.',
    coverImageUrl: s3('covers/replit.png'),
    coverTheme: 'dark',
    coverHeadline: 'From thought to software',
    builtWith: 'Replit Sandboxes & Claude 3.5 Sonnet',
    techStack: ['Nix', 'Python', 'PostgreSQL', 'Docker'],
    websiteUrl: 'https://replit.com',
    users: 38000,
    mrr: 27500,
    category: 'Dev Tools',
    upvotes: 840,
    contributors: [contributor('c9', 'Elena Rostova')],
    needsHelpWith: 'Telemetry for sandbox execution and container recovery',
    contactEmail: 'elena@replit.com',
    launchedAt: '2024-09-05',
    helpCategories: [
      { id: 'h15', label: 'Infra / Sandboxing', peopleCount: 68, avatarUrl: avatar('h15') },
    ],
  },
  {
    id: '15',
    slug: 'midjourney-buddy',
    name: 'PromptRefine',
    emoji: '🎨',
    tagline: 'Photorealistic image prompt engineering and parameter tuning assistant.',
    about:
      'Enhance simple text concepts into nuanced photorealistic prompts complete with lighting models, lenses, film stocks, and aspect ratios.',
    story:
      'Created to turn vague creative visions into breathtaking Midjourney & Flux renders without memorizing esoteric camera tags.',
    coverImageUrl: s3('covers/promptrefine.png'),
    coverTheme: 'sunset',
    coverHeadline: 'Picture-perfect prompt crafting',
    builtWith: 'Flux API & GPT-4o mini',
    techStack: ['Next.js', 'Diffusion', 'Flux', 'Tailwind'],
    websiteUrl: 'https://promptrefine.art',
    users: 9400,
    mrr: 5800,
    category: 'Fun',
    upvotes: 460,
    contributors: [contributor('c10', 'Marcus Brody')],
    needsHelpWith: 'Discord bot scaling and queue management',
    contactEmail: 'marcus@promptrefine.art',
    launchedAt: '2023-07-12',
    helpCategories: [
      { id: 'h16', label: 'Discord / Community', peopleCount: 57, avatarUrl: avatar('h16') },
    ],
  },
  {
    id: '16',
    slug: 'calorify',
    name: 'Calorify',
    emoji: '🥗',
    tagline: 'Snap a picture of your meal and track macros instantly with vision AI.',
    about:
      'Point your phone at any plate of food or grocery receipt to get instant, accurate macro breakdowns and micronutrient summaries.',
    story:
      'Manual food logging is why 90% of calorie counting apps get uninstalled after week one. Vision makes it effortless.',
    coverImageUrl: s3('covers/calorify.png'),
    coverTheme: 'mint',
    coverHeadline: 'Effortless macro logging with photos',
    builtWith: 'GPT-4 Vision & USDA FoodData Central',
    techStack: ['Vision AI', 'React Native', 'Supabase', 'Python'],
    websiteUrl: 'https://calorify.health',
    users: 11200,
    mrr: 8900,
    category: 'Lifestyle',
    upvotes: 495,
    contributors: [contributor('c11', 'Sarah Jenkins')],
    needsHelpWith: 'Regional cuisine nutrition dataset calibration',
    contactEmail: 'sarah@calorify.health',
    launchedAt: '2024-02-14',
    helpCategories: [
      { id: 'h17', label: 'Data Scraping', peopleCount: 38, avatarUrl: avatar('h17') },
    ],
  },
  {
    id: '17',
    slug: 'pitch-roast',
    name: 'PitchRoast',
    emoji: '🔥',
    tagline: 'Brutal AI critique and stress-testing for startup pitch decks.',
    about:
      'Upload your slide deck or one-pager to get an unvarnished, savage VC-style teardown pointing out market size flaws and unit economic pitfalls.',
    story:
      'Your friends and family are too nice to tell you your SaaS idea makes no sense. PitchRoast gives you the brutal truth before investors do.',
    coverImageUrl: s3('covers/pitchroast.png'),
    coverTheme: 'sunset',
    coverHeadline: 'Get roasted before your investors do',
    builtWith: 'Claude 3.5 Sonnet & PDF parser',
    techStack: ['PDF.js', 'Next.js', 'Claude', 'Stripe'],
    websiteUrl: 'https://pitchroast.xyz',
    users: 6400,
    mrr: 3800,
    category: 'Fun',
    upvotes: 540,
    contributors: [contributor('c12', 'Liam O Connor')],
    needsHelpWith: null,
    launchedAt: '2024-04-01',
    helpCategories: [],
  },
  {
    id: '18',
    slug: 'tldr-papers',
    name: 'TLDR Papers',
    emoji: '📚',
    tagline: 'Digest complex scientific papers into 3-minute visual executive briefs.',
    about:
      'Automatically parses ArXiv and PubMed preprints, extracting primary findings, methodology caveats, and generating interactive concept graphs.',
    story:
      'Over 200 AI papers are published every single day. Nobody has time to read 20 pages of math just to evaluate one architectural trick.',
    coverImageUrl: s3('covers/tldrpapers.png'),
    coverTheme: 'light',
    coverHeadline: 'Stay ahead of cutting-edge research',
    builtWith: 'Arxiv API & Gemini 1.5 Pro',
    techStack: ['Gemini', 'Python', 'FastAPI', 'Next.js'],
    websiteUrl: 'https://tldrpapers.org',
    users: 8700,
    mrr: 5200,
    category: 'Productivity',
    upvotes: 380,
    contributors: [contributor('c13', 'Yuki Tanaka')],
    needsHelpWith: 'ArXiv scraper maintenance & LaTeX equation rendering',
    contactEmail: 'yuki@tldrpapers.org',
    launchedAt: '2023-12-05',
    helpCategories: [
      { id: 'h18', label: 'Frontend / MathJax', peopleCount: 22, avatarUrl: avatar('h18') },
    ],
  },
  {
    id: '19',
    slug: 'invoice-ninja-ai',
    name: 'InvoiceZen',
    emoji: '🧾',
    tagline: 'Autonomous accounts receivable and payment reconciliation for agencies.',
    about:
      'Connects your bank feed and billing tools to automatically chase overdue invoices with polite, escalation-aware emails and record receipts.',
    story:
      'Freelancers and small agencies lose thousands every quarter because following up on unpaid bills feels uncomfortable and takes hours.',
    coverImageUrl: s3('covers/invoicezen.png'),
    coverTheme: 'mint',
    coverHeadline: 'Get paid on time without the awkwardness',
    builtWith: 'Plaid, Stripe & GPT-4o',
    techStack: ['Plaid', 'Stripe', 'Node.js', 'PostgreSQL'],
    websiteUrl: 'https://invoicezen.co',
    users: 4100,
    mrr: 11400,
    category: 'SaaS',
    upvotes: 430,
    contributors: [contributor('c14', 'Priya Patel')],
    needsHelpWith: 'Multi-currency conversion & QuickBooks sync',
    contactEmail: 'priya@invoicezen.co',
    launchedAt: '2023-08-15',
    helpCategories: [
      { id: 'h19', label: 'Accounting / Plaid', peopleCount: 33, avatarUrl: avatar('h19') },
    ],
  },
  {
    id: '20',
    slug: 'dog-translator',
    name: 'BarkLingo',
    emoji: '🐶',
    tagline: 'Funny acoustic bark analysis that decodes what your pet is demanding.',
    about:
      'Record your dog barking or whimpering and let AI classify their emotional state with hilarious voiceover translations.',
    story:
      'Built as a joke for our own rescue dog who wouldn’t stop barking at the mailman; turned into a viral sensation with millions of downloads.',
    coverImageUrl: s3('covers/barklingo.png'),
    coverTheme: 'sunset',
    coverHeadline: 'Finally understand your dog',
    builtWith: 'CoreML sound classifier & ElevenLabs',
    techStack: ['Audio Processing', 'ElevenLabs', 'Swift', 'iOS'],
    websiteUrl: 'https://barklingo.app',
    users: 34000,
    mrr: 8200,
    category: 'Fun',
    upvotes: 820,
    contributors: [contributor('c15', 'Carlos Mendez')],
    needsHelpWith: null,
    launchedAt: '2024-03-20',
    helpCategories: [],
  },
  {
    id: '21',
    slug: 'zen-journal',
    name: 'ZenJournal',
    emoji: '🧘',
    tagline: 'Voice-first AI diary that reflects your thoughts and spots burnout.',
    about:
      'Speak your mind at the end of the day. ZenJournal transcribes, identifies recurring stressors, and offers CBT-informed journal reflections.',
    story:
      'Staring at a blank journal page after a stressful day is intimidating. Speaking for 2 minutes to a thoughtful listener is cathartic.',
    coverImageUrl: s3('covers/zenjournal.png'),
    coverTheme: 'mint',
    coverHeadline: 'Clear your mind in 2 minutes',
    builtWith: 'Whisper & Claude 3.5 Haiku',
    techStack: ['Whisper', 'Audio', 'Next.js', 'Tailwind'],
    websiteUrl: 'https://zenjournal.me',
    users: 5900,
    mrr: 4300,
    category: 'Lifestyle',
    upvotes: 310,
    contributors: [contributor('c16', 'Aisha Al-Mansoor')],
    needsHelpWith: 'Voice transcription latency & end-to-end encryption',
    contactEmail: 'aisha@zenjournal.me',
    launchedAt: '2024-04-18',
    helpCategories: [
      { id: 'h20', label: 'Security / Crypto', peopleCount: 26, avatarUrl: avatar('h20') },
    ],
  },
  {
    id: '22',
    slug: 'lead-sniper',
    name: 'LeadSniper',
    emoji: '🎯',
    tagline: 'High-intent B2B prospect discovery triggered by hiring and tech changes.',
    about:
      'Scans Github repos, job boards, and tech stack telemetry to alert sales teams the moment companies experience pain points you solve.',
    story:
      'Cold outbound is dead; warm timing is everything. LeadSniper turns public developer signals into high-converting prospect lists.',
    coverImageUrl: s3('covers/leadsniper.png'),
    coverTheme: 'dark',
    coverHeadline: 'Reach buyers at the exact right second',
    builtWith: 'Scrapy, Elasticsearch & OpenAI',
    techStack: ['Scrapy', 'Elasticsearch', 'Python', 'React'],
    websiteUrl: 'https://leadsniper.io',
    users: 2800,
    mrr: 18200,
    category: 'SaaS',
    upvotes: 520,
    contributors: [
      contributor('c17', 'Devon Vance'),
      contributor('user_123', 'John Doe'),
    ],
    needsHelpWith: 'Webhook verification & deduplication at scale',
    contactEmail: 'devon@leadsniper.io',
    launchedAt: '2023-06-10',
    helpCategories: [
      { id: 'h21', label: 'Infra / Queueing', peopleCount: 44, avatarUrl: avatar('h21') },
    ],
  },
  {
    id: '23',
    slug: 'git-explain',
    name: 'GitExplain',
    emoji: '🐙',
    tagline: 'Plain-English explanations for cryptic merge conflicts and git history.',
    about:
      'Paste terrifying git rebase conflict diffs or obscure detached HEAD errors and get step-by-step commands to resolve them safely.',
    story:
      'Everyone pretends they know git rebase until their branch detaches into git limbo and they consider deleting the whole repo.',
    coverImageUrl: s3('covers/gitexplain.png'),
    coverTheme: 'light',
    coverHeadline: 'Never fear git rebase again',
    builtWith: 'Wasm Git & GPT-4o mini',
    techStack: ['Git', 'WebAssembly', 'TypeScript', 'Next.js'],
    websiteUrl: 'https://gitexplain.dev',
    users: 14200,
    mrr: 1900,
    category: 'Dev Tools',
    upvotes: 610,
    contributors: [contributor('c18', 'Chloe Bennett')],
    needsHelpWith: null,
    launchedAt: '2023-11-04',
    helpCategories: [],
  },
  {
    id: '24',
    slug: 'habit-craft',
    name: 'HabitCraft',
    emoji: '🏆',
    tagline: 'Gamified habit building with an AI dungeon master and loot drops.',
    about:
      'Turn your morning workouts, reading goals, and hydration habits into XP, equipment upgrades, and cooperative boss battles with friends.',
    story:
      'Streaks alone are boring; quest rewards and leveling up turn mundane daily discipline into an addictive role-playing game.',
    coverImageUrl: s3('covers/habitcraft.png'),
    coverTheme: 'sunset',
    coverHeadline: 'Level up your real-life stats',
    builtWith: 'Supabase & Pixel art sprites',
    techStack: ['React Native', 'Supabase', 'Game Loop', 'Tailwind'],
    websiteUrl: 'https://habitcraft.gg',
    users: 16500,
    mrr: 7200,
    category: 'Lifestyle',
    upvotes: 470,
    contributors: [contributor('c19', 'Lucas Meyer')],
    needsHelpWith: 'iOS push notification retention triggers',
    contactEmail: 'lucas@habitcraft.gg',
    launchedAt: '2024-02-01',
    helpCategories: [
      { id: 'h22', label: 'Growth / Push Notifications', peopleCount: 51, avatarUrl: avatar('h22') },
    ],
  },
  {
    id: '25',
    slug: 'legal-lens',
    name: 'LegalLens',
    emoji: '⚖️',
    tagline: 'Vendor contract review that redlines predatory clauses in seconds.',
    about:
      'Upload commercial vendor agreements, NDAs, or SaaS terms to spot auto-renew trapdoors, unlimited liability clauses, and IP transfers.',
    story:
      'Early-stage founders sign enterprise vendor contracts blind because outside counsel costs $800/hour. LegalLens highlights the hidden landmines.',
    coverImageUrl: s3('covers/legallens.png'),
    coverTheme: 'dark',
    coverHeadline: 'Sign contracts without surprise traps',
    builtWith: 'LlamaIndex & Claude 3.5 Sonnet',
    techStack: ['Python', 'LlamaIndex', 'PDF Parsing', 'React'],
    websiteUrl: 'https://legallens.ai',
    users: 3200,
    mrr: 14800,
    category: 'SaaS',
    upvotes: 380,
    contributors: [contributor('c20', 'Naomi Klein')],
    needsHelpWith: null,
    launchedAt: '2023-05-18',
    helpCategories: [],
  },
  {
    id: '26',
    slug: 'roast-my-resume',
    name: 'ResumeRoast',
    emoji: '📄',
    tagline: 'Action-oriented resume rewrites tailored to pass modern ATS filters.',
    about:
      'Paste your job target URL and resume to get quantifiable bullet points, keyword coverage scores, and recruiter readability insights.',
    story:
      'Job seekers send 500 applications into ATS black holes. ResumeRoast reconstructs passive bullets into high-impact metric statements.',
    coverImageUrl: s3('covers/resumeroast.png'),
    coverTheme: 'mint',
    coverHeadline: 'Land interviews, not auto-rejections',
    builtWith: 'Next.js & GPT-4o',
    techStack: ['Next.js', 'OpenAI', 'Tailwind', 'Vercel'],
    websiteUrl: 'https://resumeroast.me',
    users: 22000,
    mrr: 6300,
    category: 'Productivity',
    upvotes: 690,
    contributors: [contributor('c21', 'Omar Farooq')],
    needsHelpWith: null,
    launchedAt: '2024-01-10',
    helpCategories: [],
  },
  {
    id: '27',
    slug: 'sound-bath',
    name: 'SoundBath',
    emoji: '🌊',
    tagline: 'Algorithmic binaural audioscapes for deep focus and neurodivergent flow.',
    about:
      'Generates infinitely evolving, non-looping pink noise, rainfall, and low-frequency resonance tuned to alpha and theta brainwave frequencies.',
    story:
      'Standard lo-fi music gets distracting after 30 minutes. SoundBath creates endless subtle soundscapes that melt into the background.',
    coverImageUrl: s3('covers/soundbath.png'),
    coverTheme: 'sunset',
    coverHeadline: 'Slip into deep uninterrupted flow',
    builtWith: 'Web Audio API & Tone.js',
    techStack: ['Web Audio API', 'Tone.js', 'Canvas', 'TypeScript'],
    websiteUrl: 'https://soundbath.fm',
    users: 12800,
    mrr: 3900,
    category: 'Lifestyle',
    upvotes: 410,
    contributors: [contributor('c22', 'Hannah Schmidt')],
    needsHelpWith: null,
    launchedAt: '2023-09-28',
    helpCategories: [],
  },
  {
    id: '28',
    slug: 'api-mock-genius',
    name: 'APIMockGenius',
    emoji: '🔌',
    tagline: 'Generate realistic stateful mock APIs and WebSocket endpoints in 1 click.',
    about:
      'Feed an OpenAPI spec or describe your schema to instantly get a live, stateful REST/GraphQL mock server with authentication and latency simulation.',
    story:
      'Frontend development shouldn’t be blocked for 3 sprints while waiting for the backend team to build staging endpoints.',
    coverImageUrl: s3('covers/apimock.png'),
    coverTheme: 'light',
    coverHeadline: 'Ship frontend before backend is built',
    builtWith: 'Cloudflare Workers & Faker.js',
    techStack: ['Cloudflare Workers', 'TypeScript', 'OpenAPI', 'Web'],
    websiteUrl: 'https://apimockgenius.dev',
    users: 7100,
    mrr: 5900,
    category: 'Dev Tools',
    upvotes: 440,
    contributors: [contributor('c23', 'Kevin Zhao')],
    needsHelpWith: 'OpenAPI 3.1 generator & stateful graph traversal',
    contactEmail: 'kevin@apimock.dev',
    launchedAt: '2024-03-02',
    helpCategories: [
      { id: 'h23', label: 'API / Schema', peopleCount: 39, avatarUrl: avatar('h23') },
    ],
  },
  {
    id: '29',
    slug: 'recipe-remix',
    name: 'PantryRemix',
    emoji: '🍳',
    tagline: 'Delicious gourmet meals created exclusively from whatever is in your fridge.',
    about:
      'Snap a picture of your chaotic open fridge or pantry shelves and receive step-by-step chef recipes that prevent food waste.',
    story:
      'Everyone has half a bell pepper, a tub of sour cream, and leftover rice that end up in the trash. PantryRemix transforms leftovers into feasts.',
    coverImageUrl: s3('covers/pantryremix.png'),
    coverTheme: 'mint',
    coverHeadline: 'Turn random fridge scraps into dinner',
    builtWith: 'Vision AI & Recipe Graph',
    techStack: ['Next.js', 'Vision AI', 'Tailwind', 'Supabase'],
    websiteUrl: 'https://pantryremix.app',
    users: 9800,
    mrr: 2800,
    category: 'Lifestyle',
    upvotes: 360,
    contributors: [contributor('c24', 'Isabella Rossi')],
    needsHelpWith: null,
    launchedAt: '2024-04-22',
    helpCategories: [],
  },
  {
    id: '30',
    slug: 'cold-outreach-pro',
    name: 'OutboundForge',
    emoji: '✉️',
    tagline: 'Hyper-personalized cold email synthesis with automated inbox warmups.',
    about:
      'Deeply researches recipient podcasts, recent LinkedIn posts, and company press to draft non-spammy, tailored introductory outreach.',
    story:
      'Generic email templates go straight into spam. OutboundForge writes emails that look like you spent an hour researching before reaching out.',
    coverImageUrl: s3('covers/outboundforge.png'),
    coverTheme: 'dark',
    coverHeadline: 'Cold emails that actually get replies',
    builtWith: 'Resend API & Claude 3.5 Sonnet',
    techStack: ['Email Deliverability', 'PostgreSQL', 'Python', 'Next.js'],
    websiteUrl: 'https://outboundforge.io',
    users: 4800,
    mrr: 21300,
    category: 'SaaS',
    upvotes: 590,
    contributors: [contributor('c25', 'Tyler Reed')],
    needsHelpWith: 'Deliverability & SPF/DKIM verification algorithms',
    contactEmail: 'tyler@outboundforge.io',
    launchedAt: '2023-04-10',
    helpCategories: [
      { id: 'h24', label: 'Email Infra', peopleCount: 62, avatarUrl: avatar('h24') },
    ],
  },
];

export const COMMENTS: Record<string, Comment[]> = {
  perplexity: [
    {
      id: 'cm1',
      author: 'Maya Singh',
      avatarUrl: avatar('c3'),
      body: 'The source-first answer format is still one of the most useful patterns in AI search.',
      createdAt: '2024-08-01T10:00:00.000Z',
    },
    {
      id: 'cm2',
      author: 'Alex Chen',
      avatarUrl: avatar('c2'),
      body: 'I use this literally every day for research. Way faster than digging through Google ads.',
      createdAt: '2024-08-03T14:15:00.000Z',
    },
    {
      id: 'cm3',
      author: 'Kevin Zhao',
      avatarUrl: avatar('c23'),
      body: 'The speed of citations has gotten absurdly fast in the last few updates.',
      createdAt: '2024-08-06T18:22:00.000Z',
    },
    {
      id: 'cm4',
      author: 'Elena Rostova',
      avatarUrl: avatar('c9'),
      body: 'How are you handling freshness on fast-breaking news? The latency is impressive.',
      createdAt: '2024-08-09T09:40:00.000Z',
    },
  ],
  cursor: [
    {
      id: 'cm5',
      author: 'Alex Chen',
      avatarUrl: avatar('c2'),
      body: 'The codebase-aware editing workflow is the part I keep coming back to.',
      createdAt: '2024-08-02T14:30:00.000Z',
    },
    {
      id: 'cm6',
      author: 'John Doe',
      avatarUrl: avatar('user_123'),
      body: 'Command+K multi-file edits saved me about 12 hours this week alone.',
      createdAt: '2024-08-04T11:20:00.000Z',
    },
    {
      id: 'cm7',
      author: 'Chloe Bennett',
      avatarUrl: avatar('c18'),
      body: 'The indexer on massive monorepos is super impressive. Barely any lag.',
      createdAt: '2024-08-07T16:05:00.000Z',
    },
  ],
  v0: [
    {
      id: 'cm8',
      author: 'Sofia Martin',
      avatarUrl: avatar('c5'),
      body: 'Really useful for getting from an interface idea to something concrete quickly.',
      createdAt: '2024-08-05T09:15:00.000Z',
    },
    {
      id: 'cm9',
      author: 'John Doe',
      avatarUrl: avatar('user_123'),
      body: 'Being able to copy the Shadcn components directly into my codebase is a cheat code.',
      createdAt: '2024-08-08T13:40:00.000Z',
    },
    {
      id: 'cm10',
      author: 'Leo Andersson',
      avatarUrl: avatar('c6'),
      body: 'The conversational iteration on UI states feels super natural.',
      createdAt: '2024-08-10T10:12:00.000Z',
    },
  ],
  bolt: [
    {
      id: 'cm11',
      author: 'Noah Williams',
      avatarUrl: avatar('c4'),
      body: 'Shipping WebContainers into the browser makes the whole fullstack loop immediate.',
      createdAt: '2024-08-03T11:00:00.000Z',
    },
    {
      id: 'cm12',
      author: 'John Doe',
      avatarUrl: avatar('user_123'),
      body: 'The instant preview without needing a local terminal setup is huge for prototyping.',
      createdAt: '2024-08-05T15:20:00.000Z',
    },
    {
      id: 'cm13',
      author: 'Taylor Brooks',
      avatarUrl: avatar('c8'),
      body: 'Can confirm, this replaced my local sandbox setup for quick React experiments.',
      createdAt: '2024-08-08T17:35:00.000Z',
    },
  ],
  'prompt-smith': [
    {
      id: 'cm14',
      author: 'Alex Chen',
      avatarUrl: avatar('c2'),
      body: 'Catching prompt regressions before deployment has saved our team so many late-night panics.',
      createdAt: '2024-08-04T08:30:00.000Z',
    },
    {
      id: 'cm15',
      author: 'Elena Rostova',
      avatarUrl: avatar('c9'),
      body: 'The diff viewer between model output evaluations is clean and super intuitive.',
      createdAt: '2024-08-07T12:45:00.000Z',
    },
  ],
  'meme-forge': [
    {
      id: 'cm16',
      author: 'Jamie Park',
      avatarUrl: avatar('c7'),
      body: 'The timing of the captions on the TikTok templates is scary accurate.',
      createdAt: '2024-08-02T19:20:00.000Z',
    },
    {
      id: 'cm17',
      author: 'Liam O Connor',
      avatarUrl: avatar('c12'),
      body: 'Our Discord server has been spamming this non-stop. Hilarious output.',
      createdAt: '2024-08-06T14:10:00.000Z',
    },
  ],
  'code-napkin': [
    {
      id: 'cm18',
      author: 'Kevin Zhao',
      avatarUrl: avatar('c23'),
      body: 'The Terraform generation from simple box-and-arrow diagrams actually works on AWS.',
      createdAt: '2024-08-01T15:10:00.000Z',
    },
    {
      id: 'cm19',
      author: 'Devon Vance',
      avatarUrl: avatar('c17'),
      body: 'Cleanest diagram-to-code experience I have tried so far.',
      createdAt: '2024-08-05T18:00:00.000Z',
    },
  ],
  'sleep-bot': [
    {
      id: 'cm20',
      author: 'Sarah Jenkins',
      avatarUrl: avatar('c11'),
      body: 'The correlation between my late caffeine cutoff and REM duration was eye-opening.',
      createdAt: '2024-08-03T07:15:00.000Z',
    },
  ],
  'sql-whisperer': [
    {
      id: 'cm21',
      author: 'Priya Patel',
      avatarUrl: avatar('c14'),
      body: 'Finally a text-to-SQL tool that understands complex group by joins without hallucinating table columns.',
      createdAt: '2024-08-04T16:30:00.000Z',
    },
    {
      id: 'cm22',
      author: 'Tyler Reed',
      avatarUrl: avatar('c25'),
      body: 'Gave this to our growth team and our analytics backlog dropped to zero.',
      createdAt: '2024-08-09T11:45:00.000Z',
    },
  ],
  granola: [
    {
      id: 'cm23',
      author: 'Taylor Brooks',
      avatarUrl: avatar('c8'),
      body: 'Not having a creepy bot join the call is the single best decision in this product.',
      createdAt: '2024-08-02T13:10:00.000Z',
    },
    {
      id: 'cm24',
      author: 'John Doe',
      avatarUrl: avatar('user_123'),
      body: 'It blends my own messy bullet points with the actual transcript effortlessly.',
      createdAt: '2024-08-06T17:50:00.000Z',
    },
  ],
  'lead-sniper': [
    {
      id: 'cm25',
      author: 'Tyler Reed',
      avatarUrl: avatar('c25'),
      body: 'The hiring trigger alerts convert at 4x our standard cold email campaigns.',
      createdAt: '2024-08-05T10:15:00.000Z',
    },
  ],
};

export const SESSION: Session = {
  user: {
    id: 'user_123',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'user',
    icon: avatar('user_123'),
  },
};

export const HELP_OFFERS: Record<string, HelpOffer[]> = {
  // --- Inbound Offers to John Doe's apps (user_123) ---
  perplexity: [
    {
      id: 'ho-in-1',
      appSlug: 'perplexity',
      senderId: 'c3',
      senderName: 'Maya Singh',
      senderAvatarUrl: avatar('c3'),
      senderContact: 'maya@v0.dev',
      message:
        'I specialize in citation UX and source verification pipelines. Would love to help polish the citation preview modals and accuracy indicators!',
      status: 'pending',
      createdAt: '2024-08-12T14:20:00.000Z',
    },
    {
      id: 'ho-in-2',
      appSlug: 'perplexity',
      senderId: 'c18',
      senderName: 'Chloe Bennett',
      senderAvatarUrl: avatar('c18'),
      senderContact: 'chloe@gitexplain.dev',
      message:
        'I can help wire up streaming responses with smooth chunk rendering and zero layout shift on mobile devices.',
      status: 'accepted',
      createdAt: '2024-08-06T09:15:00.000Z',
      respondedAt: '2024-08-07T11:30:00.000Z',
    },
    {
      id: 'ho-in-3',
      appSlug: 'perplexity',
      senderId: 'c23',
      senderName: 'Kevin Zhao',
      senderAvatarUrl: avatar('c23'),
      senderContact: 'kevin@apimock.dev',
      message:
        'I built a custom electron wrapper and system tray hotkey launcher if you want to ship a native desktop companion app.',
      status: 'declined',
      createdAt: '2024-07-28T16:00:00.000Z',
      respondedAt: '2024-07-29T10:00:00.000Z',
    },
    {
      id: 'ho-in-4',
      appSlug: 'perplexity',
      senderId: 'c14',
      senderName: 'Priya Patel',
      senderAvatarUrl: avatar('c14'),
      senderContact: 'priya@invoicezen.co',
      message:
        'Would love to benchmark search index latency across multi-lingual datasets and optimize embedding retrieval caching.',
      status: 'pending',
      createdAt: '2024-08-11T18:40:00.000Z',
    },
  ],

  'prompt-smith': [
    {
      id: 'ho-in-5',
      appSlug: 'prompt-smith',
      senderId: 'c2',
      senderName: 'Alex Chen',
      senderAvatarUrl: avatar('c2'),
      senderContact: 'alex@cursor.com',
      message:
        'We have automated eval suites for code generation models. I can contribute a standardized testing runner for system prompt regressions.',
      status: 'pending',
      createdAt: '2024-08-13T11:10:00.000Z',
    },
    {
      id: 'ho-in-6',
      appSlug: 'prompt-smith',
      senderId: 'c9',
      senderName: 'Elena Rostova',
      senderAvatarUrl: avatar('c9'),
      senderContact: 'elena@replit.com',
      message:
        'Willing to help optimize few-shot prompt compression and latency metrics across OpenRouter endpoints.',
      status: 'accepted',
      createdAt: '2024-08-08T10:20:00.000Z',
      respondedAt: '2024-08-09T14:00:00.000Z',
    },
    {
      id: 'ho-in-7',
      appSlug: 'prompt-smith',
      senderId: 'c25',
      senderName: 'Tyler Reed',
      senderAvatarUrl: avatar('c25'),
      senderContact: 'tyler@outboundforge.io',
      message:
        'I have experience integrating prompt version control with GitHub actions for automated CI gating.',
      status: 'pending',
      createdAt: '2024-08-14T08:50:00.000Z',
    },
  ],

  'meme-forge': [
    {
      id: 'ho-in-8',
      appSlug: 'meme-forge',
      senderId: 'c7',
      senderName: 'Jamie Park',
      senderAvatarUrl: avatar('c7'),
      senderContact: 'jamie@suno.com',
      message:
        'I can assist with client-side WebAssembly audio synchronization so background beats match meme punchlines automatically.',
      status: 'pending',
      createdAt: '2024-08-12T15:30:00.000Z',
    },
    {
      id: 'ho-in-9',
      appSlug: 'meme-forge',
      senderId: 'c12',
      senderName: 'Liam O Connor',
      senderAvatarUrl: avatar('c12'),
      senderContact: 'liam@pitchroast.xyz',
      message:
        'Happy to help curate viral meme templates and trending Twitter reaction formats to keep the generator fresh.',
      status: 'accepted',
      createdAt: '2024-08-04T12:00:00.000Z',
      respondedAt: '2024-08-05T09:30:00.000Z',
    },
  ],

  'sleep-bot': [
    {
      id: 'ho-in-10',
      appSlug: 'sleep-bot',
      senderId: 'c11',
      senderName: 'Sarah Jenkins',
      senderAvatarUrl: avatar('c11'),
      senderContact: 'sarah@calorify.health',
      message:
        'I have integrated Apple HealthKit and Whoop sleep stage streams in production React Native apps. Can build the background sync engine.',
      status: 'pending',
      createdAt: '2024-08-10T17:15:00.000Z',
    },
    {
      id: 'ho-in-11',
      appSlug: 'sleep-bot',
      senderId: 'c19',
      senderName: 'Lucas Meyer',
      senderAvatarUrl: avatar('c19'),
      senderContact: 'lucas@habitcraft.gg',
      message:
        'I can design interactive sleep debt visualization charts and circadian rhythm recovery badges.',
      status: 'accepted',
      createdAt: '2024-08-03T14:45:00.000Z',
      respondedAt: '2024-08-04T10:10:00.000Z',
    },
  ],

  'sql-whisperer': [
    {
      id: 'ho-in-12',
      appSlug: 'sql-whisperer',
      senderId: 'c28',
      senderName: 'Danielle Wu',
      senderAvatarUrl: avatar('c28'),
      senderContact: 'danielle@analytics.dev',
      message:
        'Can help optimize schema foreign-key graph traversal and write automated query explain-plan validation tests.',
      status: 'pending',
      createdAt: '2024-08-13T19:25:00.000Z',
    },
  ],

  // --- Outbound Offers sent BY John Doe (user_123) to other apps ---
  v0: [
    {
      id: 'ho-out-1',
      appSlug: 'v0',
      senderId: 'user_123',
      senderName: 'John Doe',
      senderAvatarUrl: avatar('user_123'),
      senderContact: 'john@example.com',
      message:
        'I can help benchmark generative UI response times across different LLM backends and build custom tailwind theme export presets.',
      status: 'pending',
      createdAt: '2024-08-11T16:45:00.000Z',
    },
  ],

  bolt: [
    {
      id: 'ho-out-2',
      appSlug: 'bolt',
      senderId: 'user_123',
      senderName: 'John Doe',
      senderAvatarUrl: avatar('user_123'),
      senderContact: 'john@example.com',
      message:
        'I can help with containerized WebContainer builds and caching for rapid preview spins without reload latency.',
      status: 'accepted',
      createdAt: '2024-08-05T10:00:00.000Z',
      respondedAt: '2024-08-06T12:00:00.000Z',
    },
    {
      id: 'ho-comm-1',
      appSlug: 'bolt',
      senderId: 'c5',
      senderName: 'Sofia Martin',
      senderAvatarUrl: avatar('c5'),
      senderContact: 'sofia@gamma.app',
      message:
        'Happy to collaborate on growth tactics and developer marketing for in-browser environments.',
      status: 'accepted',
      createdAt: '2024-08-08T09:10:00.000Z',
      respondedAt: '2024-08-09T11:00:00.000Z',
    },
  ],

  cursor: [
    {
      id: 'ho-out-3',
      appSlug: 'cursor',
      senderId: 'user_123',
      senderName: 'John Doe',
      senderAvatarUrl: avatar('user_123'),
      senderContact: 'john@example.com',
      message:
        'Would love to help benchmark latency on diff-streaming models for large file edits and syntax highlighting preservation.',
      status: 'pending',
      createdAt: '2024-08-12T13:20:00.000Z',
    },
  ],

  'replit-agent': [
    {
      id: 'ho-out-4',
      appSlug: 'replit-agent',
      senderId: 'user_123',
      senderName: 'John Doe',
      senderAvatarUrl: avatar('user_123'),
      senderContact: 'john@example.com',
      message:
        'I have experience with sandboxed execution environments and container lifecycle telemetry during automated package installation.',
      status: 'pending',
      createdAt: '2024-08-13T15:00:00.000Z',
    },
  ],

  granola: [
    {
      id: 'ho-out-5',
      appSlug: 'granola',
      senderId: 'user_123',
      senderName: 'John Doe',
      senderAvatarUrl: avatar('user_123'),
      senderContact: 'john@example.com',
      message:
        'I can build audio segmentation filters to strip out room echo and keyboard clicks before Whisper transcription passes.',
      status: 'accepted',
      createdAt: '2024-08-02T11:00:00.000Z',
      respondedAt: '2024-08-03T15:30:00.000Z',
    },
  ],

  'midjourney-buddy': [
    {
      id: 'ho-out-6',
      appSlug: 'midjourney-buddy',
      senderId: 'user_123',
      senderName: 'John Doe',
      senderAvatarUrl: avatar('user_123'),
      senderContact: 'john@example.com',
      message:
        'I can help configure Discord slash command queueing with Redis streams to prevent ratelimit bans during spike hours.',
      status: 'declined',
      createdAt: '2024-07-25T14:10:00.000Z',
      respondedAt: '2024-07-26T18:00:00.000Z',
    },
  ],

  lovable: [
    {
      id: 'ho-out-7',
      appSlug: 'lovable',
      senderId: 'user_123',
      senderName: 'John Doe',
      senderAvatarUrl: avatar('user_123'),
      senderContact: 'john@example.com',
      message:
        'Happy to contribute edge function templates for Supabase integrations including Stripe webhooks and auth guards.',
      status: 'pending',
      createdAt: '2024-08-14T09:30:00.000Z',
    },
  ],

  'lead-sniper': [
    {
      id: 'ho-out-8',
      appSlug: 'lead-sniper',
      senderId: 'user_123',
      senderName: 'John Doe',
      senderAvatarUrl: avatar('user_123'),
      senderContact: 'john@example.com',
      message:
        'Can help with webhook verification and duplicate lead suppression algorithms using Bloom filters.',
      status: 'accepted',
      createdAt: '2024-08-01T10:00:00.000Z',
      respondedAt: '2024-08-02T16:00:00.000Z',
    },
  ],

  'api-mock-genius': [
    {
      id: 'ho-out-9',
      appSlug: 'api-mock-genius',
      senderId: 'user_123',
      senderName: 'John Doe',
      senderAvatarUrl: avatar('user_123'),
      senderContact: 'john@example.com',
      message:
        'I can write automated JSON schema validators and TypeScript type generator hooks for the mock server outputs.',
      status: 'pending',
      createdAt: '2024-08-10T12:00:00.000Z',
    },
  ],

  'tldr-papers': [
    {
      id: 'ho-out-10',
      appSlug: 'tldr-papers',
      senderId: 'user_123',
      senderName: 'John Doe',
      senderAvatarUrl: avatar('user_123'),
      senderContact: 'john@example.com',
      message:
        'I can help configure daily research digest email cron jobs using Resend and React Email templates.',
      status: 'declined',
      createdAt: '2024-07-20T10:30:00.000Z',
      respondedAt: '2024-07-21T14:00:00.000Z',
    },
  ],
};
